[tool.pydocstyle]
ignore = "D105,D107,D203,D212,D213,D413,D416"

[tool.isort]
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
atomic = true
profile = "black"
line_length = 88
skip_gitignore = true
multi_line_output = 3
force_grid_wrap = 0

[tool.mypy]
warn_unused_ignores = true
warn_redundant_casts = true
check_untyped_defs = true
ignore_missing_imports = true
disallow_untyped_defs = true
incremental = true

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
  "A",    # flake8-builtins
  "ARG",  # flake8-unused-arguments 
  "B",    # bugbear
  "C4",   # flake8-comprehensions
  "COM",  # flake8-commas
  "DTZ",  # flake8-datetimez 
  "E",    # pycodestyle, warning
  "EXE",  # flake8-executable
  "F",    # Pyflakes
  "FLY",  # flynt
  "FURB", # refurb
  "G",    # flake8-logging-format 
  "ICN",  # flake8-import-conventions 
  "LOG",  # flake8-logging
  "N",    # pep8-naming
  "PERF", # Perflint 
  "PIE",  # flake8-pie
  "PTH",  # flake8-use-pathlib 
  "Q",    # flake8-quotes
  "Q",    # flake8-quotes 
  "RET",  # flake8-return
  "RUF",  # Ruff
  "SIM",  # flake8-simplify
  "SLF",  # flake8-self 
  "T",    # print
  "W",    # pycodestyle, error
]
ignore = [
  "RUF100",  # Unused blanket noqa directive	
  "EXE001",  # Shebang is present but file is not executable	
  "PLR0911", # Too many return statements
  "PLR0913", # Too many arguments
  "RET504",  #  Unnecessary assignment
  "PLR2004", # Magic values
  "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`
  "E203",    # whitespace before ':'
]

[tool.bandit]
skips = ["B104", "B101", "B311"]


[tool.vulture]
ignore_names = ["*_missing"]

[tool.djlint]
ignore = "H031,J004"
profile = "jinja"
blank_line_after_tag = "load,extends,include"
blank_line_before_tag = "load,extends,include"
max_blank_lines = 1
